server.port: 8088

inventory:
  api:
    base-url: http://wiremock:9090

auth:
  enabled: false
  origin: "http://localhost:4200"
  jwt.key.set.uri: http://app-iam:8081/oauth2/jwks

spring:
  data:
    mongodb:
      uri: mongodb://admin:secret@mongo:27017/reportsdb?authSource=admin
      database: reportsdb
app:
  gridfs:
    bucket: reports # GridFS bucket name (prefixes fs.files/fs.chunks)

logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
    com.retailpulse: DEBUG
    com.example.report.infrastructure.feign: DEBUG
    feign: DEBUG
  file:
    name: logs/report-service.log

logbook:
  format.style: json
  obfuscate:
    parameters: [password, token, authorization]
    headers: [Authorization, Cookie, Set-Cookie]
  predicate:
    exclude:
