server.port: 8088

inventory:
  api:
    base-url: http://svc-rp-inventory:8085

auth:
  enabled: true
  origin: "http://localhost:4200"
  jwt.key.set.uri: http://app-iam:8081/oauth2/jwks

spring:
  data:
    mongodb:
      uri: mongodb://admin:secret@mongo:27017/reportsdb?authSource=admin
      database: reportsdb
app:
  gridfs:
    bucket: reports # GridFS bucket name (prefixes fs.files/fs.chunks)

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
    com.retailpulse: DEBUG
    com.example.report.infrastructure.feign: INFO
    feign: INFO
  file:
    name: logs/report-service.log

